fda_srs depends on NCIT.
Got an error executing the snakemake where it seemed fda_srs depends on NCIT being already in the database.

error: Cannot link to NCIT, Unable to find source record
Error: missing Source record where {"name":"ncit"}

So I added a dependency to ncit.COMPLETE in the load_fda_srs.